version: '3.8'

services:
  be-library-service:
    build: .
    container_name: be-library-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - backend-network
    depends_on:
      - backend-auth-postgres
      - dragonfly

  backend-auth-postgres:
    image: postgres:latest
    container_name: backend-auth-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library-app
    volumes:
      - pgdata:/var/lib/postgresql-1/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    restart: always
    command: ["--requirepass", "supersecret"]
    ports:
      - "6379:6379"
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge